name: Deploy
on: [push]

env:
  BRANCH: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into host and update repo
        # if: github.ref == 'master' || github.ref == 'staging'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/test.russellheimlich.com/htdocs
            echo "Switching to ${BRANCH}"
            git fetch
            git checkout ${BRANCH}
            git pull
            echo "Done!"
          host: ${{ secrets.SSH_HOST }}
          user: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
