name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into host and update repo
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
        uses: rlespinasse/github-slug-action@master
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test.russellheimlich.com/htdocs
            echo "Switching to ${{ env.GITHUB_REF_SLUG }}"
            git fetch
            git checkout ${{ env.GITHUB_REF_SLUG }}
            git pull
            echo "Done!"
