name: Deploy
on: [push]

env:
  BRANCH: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: SSH into host and update repo
        # if: github.ref == 'master' || github.ref == 'staging'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/test.russellheimlich.com/htdocs
            echo "Switching to $BRANCH"
            echo "Switching to ${BRANCH}"
            echo $BRANCH
            echo ${{ github.ref }}
            git fetch
            git checkout $BRANCH
            git pull
            echo "Done!"
          host: ${{ secrets.SSH_HOST }}
          user: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
