name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
     uses: fifsky/ssh-action@master
     with:
       command: |
        cd /tmp
        ls -a
      host: ${{ secrets.SSH_HOST }}
      user: ${{ secrets.SSH_USER }}
      key: ${{ secrets.SSH_PRIVATE_KEY}}
